# Generated by Django 4.0.2 on 2022-03-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_shipment_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipment_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
